<!-- Page d'édition d'un article -->
<h2><i class="fa fa-pencil"></i> Editer un nouvel article</h2>

<!-- Formulaire de saisie d'un nouvel article -->
<form class="generic-form" action="edit_post.php?id=<?= $idArticle ?>" method="post">
    <fieldset>
        <legend><i class="fa fa-sticky-note-o"></i> Article</legend>
        <ul>
            <li>
                <label for="title">Titre :</label>
                <input type="text" id="title" name="title">
            </li>
            <li>
                <label class="textarea" for="contents">Article :</label>
                <textarea id="contents" name="contents" rows="15"></textarea>
            </li>
            <li>
                <label for="author">Auteur :</label>
                <select id="author" name="author">
                    <?php foreach($authors as $author): ?>
                        <option value="<?= $author['id'] ?>"><?= $author['firstName'] ?> <?= $author['lastName'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li>
                <label for="category">Catégorie :</label>
                <select id="category" name="category">
                    <?php foreach($categories as $category): ?>
                        <option value="<?= $category['id'] ?>"><?= $category['title'] ?></option>
                    <?php endforeach ?>
                </select>
            </li>
            <li>
                <button class="button button-primary" type="submit">Enregistrer</button>
                <a class="button button-cancel" href="admin.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>