<!-- Formulaire de connexion -->
<form class="generic-form" action="register.php" method="post">
    <fieldset>
        <legend><i class="fa fa-users"></i> Nouveau Compte</legend>
        <ul>
            <li>
                <label for="username">Pseudo :</label>
                <input type="text" id="username" name="username">
            </li>
            <li>
                <label for="password">Mot de passe :</label>
                <input type="password" id="password" name="password" required>
            </li>
            <li>
                <label for="confirm_password">Mot de passe :</label>
                <input type="password" id="confirm_password" name="confirm_password" required>
            </li>
            <li>
                <button class="button button-primary" type="submit">S'inscrire</button>
                <a class="button button-cancel" href="index-blog.php">Annuler</a>
            </li>
        </ul>
    </fieldset>
</form>