<!DOCTYPE html>
<html lang="fr">
<head>

<title>CreaSoul</title>
<link href="https://fonts.googleapis.com/css?family=Open+Sans|PT+Sans+Narrow" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/creasoul-style.css">
</head>

<body>
<header>
	<a class="logo" href="creasoul.php"><img src="<?= $viewsLinks ?>img/img-créasoul/logo.png" alt="Logo de CreaSoul" /></a>
	<nav>
        <p><a href="../demos.php">Retour au Portfolio</a></p>
		<ul>
			<li><a href="#">Notre vision</a></li>
			<li><a href="#">Nos engagements</a></li>
			<li><a href="#">Votre projet</a></li>
		</ul>
	</nav>
</header>

<main>
	<section>
		<img class="illu" src="<?= $viewsLinks ?>img/img-créasoul/illu.jpg" alt="illustration">
		<h2>Lorem ipsum dolor sit amet !</h2>
		<p>
			Vivamus non diam velit. Pellentesque mollis et magna lobortis eleifend. Ut a eleifend libero. Donec in sagittis massa. Donec rutrum metus nec leo gravida, sit amet sagittis mauris pharetra. Fusce a lorem quis nulla laoreet aliquam quis vel dui. Aenean eleifend lacinia sollicitudin. Quisque condimentum euismod interdum. Etiam aliquam lectus in vulputate faucibus. Aliquam convallis elementum nisl, et fringilla libero maximus at. Cras eu nisi a velit molestie pellentesque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Maecenas ac odio sit amet dui facilisis ultricies vitae et nulla.
		</p>
		<p>
			Nunc non purus in augue venenatis mollis eu placerat eros. Morbi tortor magna, molestie ac tincidunt sed, faucibus eu nisi. Vivamus sed bibendum lacus. Sed placerat eget leo sit amet gravida. Pellentesque posuere, libero vel interdum dignissim, est urna rutrum enim, in ornare nulla ipsum quis ante. Quisque quis bibendum dui. Integer imperdiet bibendum fermentum. Praesent suscipit pellentesque est ac pellentesque. Nullam eros metus, facilisis in ante ut, pulvinar tristique nisi.
		</p>
		<p>
			Maecenas finibus neque neque, auctor mollis nisi rutrum faucibus. Nam diam purus, egestas sed ligula ac, dignissim congue tellus. Duis molestie ultricies ligula eget auctor. Mauris at pulvinar mi, eu consectetur turpis. Ut ac tempus eros. Phasellus et erat condimentum, aliquam odio in, congue nisl. Aenean non aliquam purus, ut fermentum ex. Sed sed dapibus ligula, id fermentum ipsum. Ut eget urna metus. Proin id sapien et nisi ornare malesuada id et libero.
		</p>
	</section>
	<aside>
		<article>
			<h2>LOREM IPSUM</h2>
			<p>
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus non diam velit. Pellentesque mollis et magna lobortis eleifend. Ut a eleifend libero. Donec in sagittis massa. Donec rutrum metus nec leo gravida, sit amet sagittis mauris pharetra. Fusce a lorem quis nulla laoreet aliquam quis vel dui. Aenean eleifend lacinia sollicitudin. 
			</p>
		</article>
		<article>
			<h2>LOREM IPSUM</h2>
			<p>
				Suspendisse egestas venenatis diam, sit amet tincidunt augue rutrum vel. Suspendisse rutrum congue molestie. Phasellus condimentum odio at felis luctus rhoncus. Etiam a orci nec ipsum condimentum sagittis. Vestibulum vel tortor sit amet est sagittis volutpat. Aenean tincidunt ante ac metus pulvinar ornare. Vestibulum ornare justo ut urna rutrum, id congue velit lacinia.
			</p>
		</article>
	</aside>
</main>

<footer>
</footer>
</body>
</html>