<head>
    <link rel="stylesheet" href="<?= $viewsLinks ?>css/demos.css">
</head>
<div  class="container centrage">
    <div class="row">
        <div class="col-md-12">
            <h2>Visitez l'un des sites de démonstrations</h2>
            <h3>Ils ont été réalisés lors de ma formation à la <a href="https://3wa.fr/">3w academy</a></h3>
        </div>  <!-- Fin de la class col-->
    </div>   <!-- Fin de la class row-->


    <div class="row portfolio-container">
        <!-- 1er Site -->
        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <a href="resto/index.php"><img src="resto/application/www/images/meals/bacon_cheeseburger.jpg" alt="image burger" /></a>
            </div>
            <div class="row">
                <h3>Restaurant 3WA</h3>
            </div>
         </div> <!-- Fin du 1er Site-->
        <!-- 2ème Site -->
        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <a href="myBlog/index-blog.php"><i class="fa fa-microphone"></i></a>
            </div>
            <div class="row">
                <h3>myBlog</h3>
            </div>
        </div> <!-- Fin du 2ème Site-->
        <!-- 3ème Site -->
        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <a href="Ila%20Yoga/ila_yoga.php"><img src="<?= $viewsLinks ?>img/img-IlaYoga/fond.jpg" alt="image yoga" /></a>
            </div>
            <div class="row">
                <h3>Ila Yoga</h3>
            </div>
        </div>
        <!-- Fin du 3ème Site-->
        <!-- 4ème Site -->
        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <a href="Mind%20Geek/mindgeek.php"><img src="<?= $viewsLinks ?>img/mindgeek/logo.png" alt="image mindgeek" />
            </div>
            <div class="row">
                <h3>Mind Geek</h3>
            </div>
        </div>
        <!-- Fin du 4ème Site-->
        <!-- 5ème Site -->
        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <a href="crea-soul/creasoul.php"><img src="<?= $viewsLinks ?>img/img-créasoul/logo.png" alt="image creasoul" />
            </div>
            <div class="row">
                <h3>Créasoul</h3>
            </div>
        </div>
        <!-- Fin du 5ème Site-->
        <!-- 6ème Site -->
        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <a href="redwolf/redwolf.php"><img src="<?= $viewsLinks ?>img/img-redwolf/logo.png" alt="image redwolf" />
            </div>
            <div class="row">
                <h3>Redwolf</h3>
            </div>
        </div> <!-- Fin du 6ème Site-->
    </div>



    </div>
</div>