<head>
    <link rel="stylesheet" href="<?= $viewsLinks ?>css/devinette.css">
</head>



<h4>Essayer de deviner le nombre choisi par l'ordinateur</h4>

<div class="well">
    <button id="launch" class="btn btn-success">Commencez la partie !</button>
    <button id="one_tour" class="btn btn-info">Tentative suivante</button>
    <h3>Nombre de tentatives</h3>
    <p><span class="counter"></span> Tentatives restantes</p>
    <h3>Liste des tentatives</h3>
    <ul>

    </ul>
    <p id="result"></p>
</div>


<script src="<?= $viewsLinks ?>js/devinette-nombre.js"></script>
