<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
<!-- On charge la police Courgette + Open Sans-->
<link href="https://fonts.googleapis.com/css?family=Courgette" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Open+Sans" />
<link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/normalize.css" />
 <link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/IlaYoga-home.css">
<title>Ila Yoga - Home</title>
</head>
<body >
<header>
    <p class="portfolio"><a href="../demos.php">Retour au Portfolio</a></p>
	<div>
	  	<a href="ila_yoga.php"><img src="<?= $viewsLinks ?>img/img-IlaYoga/logo.png" alt="logo"/></a>
		<nav>
			<ul>
				<li><a href="#"><span class="fa fa-calendar-o"></span><br>Agenda</a></li>
				<li><a href="#"><span class="fa fa-book"></span><br>Livre d'or</a></li>
				<li><a href="#"><span class="fa fa-photo"></span><br>Album Photo</a></li>
				<li><a href="ila_yoga_contact.php"><span class="fa fa-envelope-o"></span><br>Nous contacter</a></li>
			</ul>
		</nav>
	</div>

	<div id="slogan">
			<h1>Bougez - Respirez - Rigolez</h1>
			<h2>Et rentrez dans notre bulle de sérénité !</h2>
	</div>


</header>
<main>	
	<section id="promo">
	OFFRE PROMO : Votre premiers cours d'essai gratuit!
	</section>
	<section id="Présentation">
		<p>Ila Yoga est situé au 9, rue Magellan de Paris, à deux pas de l'avenue des Champs Elysées. Nous vous accueillons chaque jour de la semaine pour pratique votre yogz favori.</p>
		<p>Ila Yoga vous propose des cours de Hatha Yoga, Ashtanga Yoga, Yin Yoga, restorative Yoga accessibles à tous les niveaux et pour tous les âges. Et également des pratiques plus spécifiques comme les yoga pré et post natal ainsi que des cours particuliers.</p>
		<p>Le studio Ila Yoga, c'est 165m dédiés au bien-être et à l'apaisement. le shala-la salle- est situé au rez de chaussée d'un immeuble calme. On pratique sous une haute verrière qui invite la lumière du jour. L'environnementunique de notre studio yoga participe à une sérénité et à un bien être immédiats.</p>
		<p>Les facilités à votre disposition :</p>
		<ul>
				<li>Tapis de yoga et props -sangles, blocs et couvertures- à disposition</li>
				<li>Vestiaires hommes et femmes équipés de douches</li>
				<li>Salle de massage</li>
				<li>Eau et thé à discrétion</li>
			</ul>
	</section>
	<section id="Colonnes">
		<article>
			<h3>Nos cours</h3>
			<img src="<?= $viewsLinks ?>img/img-IlaYoga/1.png" alt="cours"/>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin at ante sed odio sodales rutrum. Aenean nec nulla eu urna egestas ullamcorper. Aenean gravida, mi nec porta feugiat, nulla tortor placerat leo, sed facilisis nulla nunc sit amet tellus. Aliquam erat volutpat. Donec mattis condimentum ipsum id mattis. Phasellus condimentum efficitur lacus id interdum.</p>
		</article>
		<article>
			<h3>Nos professeurs</h3>
			<img src="<?= $viewsLinks ?>img/img-IlaYoga/2.png" alt="profs"/>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin at ante sed odio sodales rutrum. Aenean nec nulla eu urna egestas ullamcorper. Aenean gravida, mi nec porta feugiat, nulla tortor placerat leo, sed facilisis nulla nunc sit amet tellus. Aliquam erat volutpat. Donec mattis condimentum ipsum id mattis. Phasellus condimentum efficitur lacus id interdum.</p>
		</article>	
		<article>
			<h3>Nos tarifs</h3>
			<img src="<?= $viewsLinks ?>img/img-IlaYoga/3.png" alt="tarifs"/>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin at ante sed odio sodales rutrum. Aenean nec nulla eu urna egestas ullamcorper. Aenean gravida, mi nec porta feugiat, nulla tortor placerat leo, sed facilisis nulla nunc sit amet tellus. Aliquam erat volutpat. Donec mattis condimentum ipsum id mattis. Phasellus condimentum efficitur lacus id interdum.</p>
		</article>		
	</section>
	
	<section id="MAP" class="map-responsive">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.4352869070003!2d2.3079229515746507!3d48.86897797918684!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fc50dc75ccf%3A0x42f0f4fa01438416!2sFranklin+D.+Roosevelt!5e0!3m2!1sfr!2sfr!4v1474970935761" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</section>
	
</main>

</body>
</html>