<head>
    <link rel="stylesheet" href="<?= $viewsLinks ?>css/jeux.css">
</head>

<div  id="page-jeux" class="container jeux centrage">
    <div class="row">
        <div class="col-md-12">
            <h2>Choisissez l'un des jeux suivants :</h2>
        </div>  <!-- Fin de la class col-->
    </div>   <!-- Fin de la class row-->


    <div class="row row-jeux">

        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <img src="<?= $viewsLinks ?>img/games/dragon.jpg" alt="image dragon" />
            </div>
            <div class="row">
                <h3>Dragon Slayer</h3>
            </div>
            <div class="row">
                <a href="dragon-slayer.php" id="dragon" type="button" class="btn btn-success">Jouez !</a>
            </div>
        </div>

        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <img src="<?= $viewsLinks ?>img/games/shifumi.jpg" alt="image shifumi" />
            </div>
            <div class="row">
                <h3>Shifumi Amélioré</h3>
            </div>
            <div class="row">
                <a href="shifumi.php" id="shifumi" type="button" class="btn btn-success">Jouez !</a>
            </div>
        </div>

        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <i class="fa fa-paint-brush" aria-hidden="true"></i>
            </div>
            <div class="row">
                <h3>Ardoise Magique</h3>
            </div>
            <div class="row">
                <a href="ardoise.php" id="ardoise" type="button" class="btn btn-success">Jouez !</a>
            </div>
        </div>

        <div class="col-md-4 col-sm-6 portfolio-item">
            <div class="row">
                <i class="fa fa-question-circle" aria-hidden="true"></i>
            </div>
            <div class="row">
                <h3>Devinette Numérique</h3>
            </div>
            <div class="row">
                <a href="devinette.php" id="devinette" type="button" class="btn btn-success">Jouez !</a>
            </div>
        </div>


    </div>  <!-- Fin de la class row-->

    <div class="row">





    </div>  <!-- Fin de la class row-->
</div>

