<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>MindGeek</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Candal|Open+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/mindgeek.css">
    <link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/mindgeek-animation.css">

</head>

<body>
<header>
    <p class="portfolio"><a href="../demos.php">Retour au Portfolio</a></p>
	<nav>
		<a class="logo" href="mindgeek.php">
			<img  src="<?= $viewsLinks ?>img/mindgeek/logo.png"alt="Logo de MindGeek" />
		</a>
		<ul>
			<li>
				<a href="mindgeek-serveurmutual.php"><i class="fa fa-users" aria-hidden="true"></i><br>Serveur Mutualisé</a>
			</li>
			<li>
				<a href="mindgeek-serveurdedie.php"><i class="fa fa-user" aria-hidden="true"></i><br>Serveur Dédié</a>
			</li>
			<li>
				<a href="mindgeek-cloud.php"><i class="fa fa-cloud" aria-hidden="true"></i><br>Solution "Cloud"</a>
			</li>
			<li>
				<a href="mindgeek-contact.php"><i class="fa fa-envelope" aria-hidden="true"></i><br>Contact</a>
			</li>
		</ul>
	</nav>
<input type="text" name="question" placeholder="Que recherchez-vous ?">
</header>
<main>
  <section id="infos-contact">
    <h2>Contactez-nous</h2>
    <div class="flex">
      <div class="colonne">
        <i class="fa fa-paper-plane" aria-hidden="true"></i>
        <p class="contact">Mail : <a>contact@3wa.fr</a></p>
      </div>
      <div class="colonne">
        <i class="fa fa-paper-plane" aria-hidden="true"></i>
        <p class="contact">Tel : <a>+33 1 40 58 19 72</a></p>
      </div>
      <div class="colonne">
        <i class="fa fa-envelope" aria-hidden="true"></i>
        <p class="contact">
	        MindGeek<br>
	        46, rue René Clair<br>
	        75018 Paris
        </p>
      </div>
    </div>
  </section>  
  <section id="MAP" class="map-responsive">
		<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2624.4352869070003!2d2.3079229515746507!3d48.86897797918684!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47e66fc50dc75ccf%3A0x42f0f4fa01438416!2sFranklin+D.+Roosevelt!5e0!3m2!1sfr!2sfr!4v1474970935761" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
	</section>

</main>

<footer>
		<ul>
			<li>
				<a href="mindgeek.phtml">Accueil</a>
			</li>
			<li>
				<a href="mindgeek-serveurmutual.phtml">Serveur Mutualisé</a>
			</li>
			<li>
				<a href="mindgeek-serveurdedie.phtml">Serveur Dédié</a>
			</li>
			<li>
				<a href="mindgeek-cloud.phtml">Solution "Cloud"</a>
			</li>
			<li>
				<a href="mindgeek-contact.phtml">Contact</a>
			</li>
			<li>
				<a href="">Se connecter</a>
			</li>
		</ul>
		<p>
			Lorem ipsum Occaecat adipisicing dolor sed magna sint sit aliquip veniam Ut ex pariatur occaecat consectetur dolor minim cillum incididunt cillum occaecat culpa incididunt est sed occaecat consequat do ut consequat eu in ut ex in cupidatat dolor commodo ullamco officia mollit tempor ad Ut tempor sint minim Duis incididunt minim sunt elit reprehenderit exercitation cillum tempor ex mollit sit officia cillum nisi ad esse aliquip in labore sint culpa anim culpa anim sit eu cupidatat irure incididunt do veniam aliquip exercitation tempor reprehenderit adipisicing minim culpa.
		</p>

</footer>
</body>
</html>