<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>MindGeek</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Candal|Open+Sans" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/mindgeek.css">
    <link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/mindgeek-animation.css">

</head>

<body>
<header>
    <p class="portfolio"><a href="../demos.php">Retour au Portfolio</a></p>
	<nav>
		<a class="logo" href="mindgeek.php">
			<img  src="<?= $viewsLinks ?>img/mindgeek/logo.png" alt="Logo de MindGeek" />
		</a>
		<ul>
			<li>
				<a href="mindgeek-serveurmutual.php"><i class="fa fa-users" aria-hidden="true"></i><br>Serveur Mutualisé</a>
			</li>
			<li>
				<a href="mindgeek-serveurdedie.php"><i class="fa fa-user" aria-hidden="true"></i><br>Serveur Dédié</a>
			</li>
			<li>
				<a href="mindgeek-cloud.php"><i class="fa fa-cloud" aria-hidden="true"></i><br>Solution "Cloud"</a>
			</li>
			<li>
				<a href="mindgeek-contact.php"><i class="fa fa-envelope" aria-hidden="true"></i><br>Contact</a>
			</li>
		</ul>
	</nav>
<input type="text" name="question" placeholder="Que recherchez-vous ?">
</header>
<main>
	<div class="explication">
		<h2>Le serveur mutualisé</h2>
		<p>
			Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat. Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat
		</p>
	</div>
	<section id="panel-offres" class="flex">
		<div class="offre">
			<h3>Perso - 100 Go</h3>
			<span>Un nom de domaine offert, idéal pour votre site perso.</span>
			<ul>
				<li>Lorem ipsum Dolore irure in</li>
				<li>Dolore minim irure fugiat et ex anim commodo cupidatat commodo</li>
				<li>Nulla amet ut in minim in id nisi</li>
			</ul>
			<h3>2.99€ HT / Mois</h3>
			<a class="commande" href="">Commander</a>
		</div>
		<div class="offre">
			<h3>Pro - 250 Go</h3>
			<span>Un nom de domaine offert, la solution professionnelle.</span>
			<ul>
				<li>Lorem ipsum Dolore irure in</li>
				<li>Dolore minim irure fugiat et ex anim commodo cupidatat commodo</li>
				<li>Nulla amet ut in minim in id nisi</li>
			</ul>
			<h3>5.99€ HT / Mois</h3>
			<a class="commande" href="">Commander</a>
		</div>
		<div class="offre">
			<h3>Performance - 500 Go</h3>
			<span>Un nom de domaine offert, pensé pour les sites techniques.</span>
			<ul>
				<li>Lorem ipsum Dolore irure in</li>
				<li>Dolore minim irure fugiat et ex anim commodo cupidatat commodo</li>
				<li>Nulla amet ut in minim in id nisi</li>
			</ul>
			<h3>9.99€ HT / Mois</h3>
			<a class="commande" href="">Commander</a>
		</div>
	</section>	



</main>

<footer>
		<ul>
			<li>
				<a href="mindgeek.phtml">Accueil</a>
			</li>
			<li>
				<a href="mindgeek-serveurmutual.phtml">Serveur Mutualisé</a>
			</li>
			<li>
				<a href="mindgeek-serveurdedie.phtml">Serveur Dédié</a>
			</li>
			<li>
				<a href="mindgeek-cloud.phtml">Solution "Cloud"</a>
			</li>
			<li>
				<a href="mindgeek-contact.phtml">Contact</a>
			</li>
			<li>
				<a href="">Se connecter</a>
			</li>
		</ul>
		<p>
			Lorem ipsum Occaecat adipisicing dolor sed magna sint sit aliquip veniam Ut ex pariatur occaecat consectetur dolor minim cillum incididunt cillum occaecat culpa incididunt est sed occaecat consequat do ut consequat eu in ut ex in cupidatat dolor commodo ullamco officia mollit tempor ad Ut tempor sint minim Duis incididunt minim sunt elit reprehenderit exercitation cillum tempor ex mollit sit officia cillum nisi ad esse aliquip in labore sint culpa anim culpa anim sit eu cupidatat irure incididunt do veniam aliquip exercitation tempor reprehenderit adipisicing minim culpa.
		</p>

</footer>
</body>
</html>