<!DOCTYPE html>
<html lang="fr">
<head>
<meta charset="UTF-8">
<title>MindGeek</title>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
<link href="https://fonts.googleapis.com/css?family=Candal|Dosis|Open+Sans" rel="stylesheet">
<link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/mindgeek.css">
<link rel="stylesheet" type="text/css" href="<?= $viewsLinks ?>css/mindgeek-animation.css">

</head>

<body>
<header>
    <p class="portfolio"><a href="../demos.php">Retour au Portfolio</a></p>
	<nav>
		<a class="logo" href="mindgeek.php">
			<img  src="<?= $viewsLinks ?>img/mindgeek/logo.png" alt="Logo de MindGeek" />
		</a>
		<ul>
			<li>
				<a href="mindgeek-serveurmutual.php">Serveur Mutualisé</a>
			</li>
			<li>
				<a href="mindgeek-serveurdedie.php">Serveur Dédié</a>
			</li>
			<li>
				<a href="mindgeek-cloud.php">Solution "Cloud"</a>
			</li>
			<li>
				<a href="mindgeek-contact.php">Contact</a>
			</li>
		</ul>
	</nav>
	<div id="pub" class="flex">
		<h1>L'hébergement à prix libre</h1>
		<p>Lorem ipsum Do labore dolor sed sunt sed magna ut laboris consequat sit sed ut laboris Excepteur voluptate in in eu minim.</p>
	</div>
<input type="text" name="question" placeholder="Que recherchez-vous ?">
</header>
<main>
	<div class="explication">
		<h2>Notre solution en 3 points</h2>
		<div class="flex">
			<div class="colonne">
                <div class="icon-offre"><i class="fa fa-cogs" aria-hidden="true"></i></div>
        <h3>Configuration</h3>
        <p>
          Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat. Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat
        </p>
			</div>
			<div class="colonne">
                <div class="icon-offre"><i class="fa fa-area-chart" aria-hidden="true"></i></div>
        <h3>Monitoring</h3>      
        <p>
          Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat. Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat
        </p>
			</div>
			<div class="colonne">
                <div class="icon-offre"><i class="fa fa-database" aria-hidden="true"></i></div>
        <h3>Sauvegarde</h3>          
        <p>
          Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat. Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat
        </p>
			</div>
		</div>
	</div>
	<div class="explication">
		<h2>Choisissez votre style d'hébergement</h2>
		<div class="flex">
			<div class="colonne">
        <h3>Serveur Mutualisé<br>19€ / mois</h3>
        <p>
          Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat. Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat
        </p>
			</div>
			<div class="colonne">
        <h3>Serveur Dédié<br>39€ / mois</h3>        
        <p>
          Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat. Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat
        </p>
			</div>
			<div class="colonne">
        <h3>Service Cloud<br>49€ / mois</h3>
        <p>
          Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat. Lorem ipsum Dolore irure in officia dolore minim irure fugiat et ex anim commodo cupidatat commodo nulla amet ut in minim in id nisi deserunt in qui amet mollit eiusmod in occaecat
        </p>
			</div>
		</div>    

	</div>



</main>

<footer>
		<ul>
			<li>
				<a href="mindgeek.phtml">Accueil</a>
			</li>
			<li>
				<a href="mindgeek-serveurmutual.phtml">Serveur Mutualisé</a>
			</li>
			<li>
				<a href="mindgeek-serveurdedie.phtml">Serveur Dédié</a>
			</li>
			<li>
				<a href="mindgeek-cloud.phtml">Solution "Cloud"</a>
			</li>
			<li>
				<a href="mindgeek-contact.phtml">Contact</a>
			</li>
			<li>
				<a href="">Se connecter</a>
			</li>
		</ul>
		<p>
			Lorem ipsum Occaecat adipisicing dolor sed magna sint sit aliquip veniam Ut ex pariatur occaecat consectetur dolor minim cillum incididunt cillum occaecat culpa incididunt est sed occaecat consequat do ut consequat eu in ut ex in cupidatat dolor commodo ullamco officia mollit tempor ad Ut tempor sint minim Duis incididunt minim sunt elit reprehenderit exercitation cillum tempor ex mollit sit officia cillum nisi ad esse aliquip in labore sint culpa anim culpa anim sit eu cupidatat irure incididunt do veniam aliquip exercitation tempor reprehenderit adipisicing minim culpa.
		</p>

</footer>
</body>
</html>