<!-- Navigation pour la page Jeux-->
<div class="container-fluid">
    <ul class="nav navbar-nav nav2">
        <li><a href="jeux.php">Page des jeux</a></li>
        <li><a href="dragon-slayer.php">Dragon Slayer</a></li>
        <li><a href="shifumi.php">Shifumi Amélioré</a></li>
        <li><a href="devinette.php">Devinette Numérique</a></li>
        <li><a href="ardoise.php">Ardoise magique</a></li>
    </ul>
</div>
