<!-- Navigation pour les pages de sites demos -->
<div class="container-fluid">
    <ul class="nav navbar-nav nav2">
        <li><a href="<?= $root ?>demos/demos.php">Accueil démos</a></li>
        <li><a href="<?= $root ?>/demos/resto/index.php">Restaurant</a></li>
        <li><a href="<?= $root ?>/demos/myBlog/index-blog.php">myBlog</a></li>
        <li><a href="<?= $root ?>/demos/Ila%20Yoga/ila_yoga.php">Ila Yoga</a></li>
        <li><a href="<?= $root ?>/demos/Mind%20Geek/mindgeek.php">Mind Geek</a></li>
        <li><a href="<?= $root ?>/demos/crea-soul/creasoul.php">Créasoul</a></li>
        <li><a href="<?= $root ?>/demos/redwolf/redwolf.php">Redwolf</a></li>
    </ul>
</div>