<head>
    <link rel="stylesheet" href="<?= $viewsLinks ?>css/shifumi.css">
</head>

<div id="image-shifumi">
    <button id="launch" class="btn btn-success">Lancez le jeu !</button>

    <div id="result" class="well hide">
        <h4>Votre choix est <span id="choixJoueur"></span> </h4>
        <h4>Le choix de votre adversaire est <span id="choixOrdi"></span> </h4>
        <h4><span id="resultat"></span></h4>
    </div>

    <script src="<?= $viewsLinks ?>js/utilities.js"></script>
    <script src="<?= $viewsLinks ?>js/shifumi.js"></script>
</div>