<?php if(isset($errorMessage)) : ?>
    <div class="notice">
        <p><?= $errorMessage ?></p>
        <?php for ($i = 0; $i < count($errors); $i++): ?>
            <p class="error-message"><?= $errors[$i] ?></p>
        <?php endfor ?>
        <br><img src="<?= $wwwUrl ?>/images/error.jpg" class="layout-center"/>
    </div>
   <?php else : ?>

    <h2><i class="fa fa-star"></i> Commande payée</h2>
    <h3>Merci d'avoir commandé au 3Wa Restaurant !</h3>
    <p>Votre commande a bien été enregistrée, elle vous sera livrée dans les plus brefs délais.</p>
    <img src="<?= $wwwUrl ?>/images/success.gif" class="layout-center"/>
    <br>
<?php endif ?>



<a href='<?= $requestUrl ?>' class="button button-primary">Accueil</a>